#include "token.hpp"
#include <string>
namespace flux {
std::string TokenTypeToString(TokenType type) {
  switch (type) {
  case TokenType::EndOfFile:
    return "EOF";
  case TokenType::Identifier:
    return "Identifier";
  case TokenType::IntegerLiteral:
    return "IntegerLiteral";
  case TokenType::StringLiteral:
    return "StringLiteral";
  case TokenType::LBrace:
    return "{";
  case TokenType::RBrace:
    return "}";
  case TokenType::LParen:
    return "(";
  case TokenType::RParen:
    return ")";
  case TokenType::Comma:
    return ",";
  case TokenType::Semicolon:
    return ";";
  case TokenType::Arrow:
    return "->";
  case TokenType::Assign:
    return "=";
  case TokenType::Plus:
    return "+";
  case TokenType::Minus:
    return "-";
  case TokenType::Star:
    return "*";
  case TokenType::Slash:
    return "/";
  case TokenType::Bang:
    return "!";
  case TokenType::EqualEqual:
    return "==";
  case TokenType::BangEqual:
    return "!=";
  case TokenType::Less:
    return "<";
  case TokenType::LessEqual:
    return "<=";
  case TokenType::Greater:
    return ">";
  case TokenType::GreaterEqual:
    return ">=";
  case TokenType::AndAnd:
    return "&&";
  case TokenType::OrOr:
    return "||";
  case TokenType::KwMachine:
    return "machine";
  case TokenType::KwState:
    return "state";
  case TokenType::KwInitial:
    return "initial";
  case TokenType::KwEvent:
    return "event";
  case TokenType::KwTransition:
    return "transition";
  case TokenType::KwGuard:
    return "guard";
  case TokenType::KwTimeout:
    return "timeout";
  case TokenType::KwFrom:
    return "from";
  case TokenType::KwOn:
    return "on";
  case TokenType::KwWhen:
    return "when";
  case TokenType::KwAfter:
    return "after";
  case TokenType::KwDo:
    return "do";
  case TokenType::KwInt:
    return "int";
  case TokenType::KwShort:
    return "short";
  case TokenType::KwChar:
    return "char";
  case TokenType::KwFloat:
    return "float";
  case TokenType::KwDouble:
    return "double";
  case TokenType::KwBool:
    return "bool";
  case TokenType::KwString:
    return "string";
  case TokenType::KwTrue:
    return "true";
  case TokenType::KwFalse:
    return "false";
  case TokenType::KwS:
    return "s";
  case TokenType::KwM:
    return "m";
  case TokenType::KwH:
    return "h";
  default:
    return "<unknown-token>";
  }
}

} // namespace flux